disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
variable_name:
  excluded: # excluded via string array
    - id
